server:
  port: 8060

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      mvc:
        routes:
          - id: calculation-service
            uri: lb://calculation-service
            predicates:
              - Path= /cities/**, /trips/**

          - id: pricing-service
            uri: lb://pricing-service
            predicates:
              - Path= /countries/**, /currencies/**, /fuels/**, /fuel-types/**

          - id: authentication-service
            uri: lb://authentication-service
            predicates:
              - Path= /accounts/**, /roles/**, /vehicles/**, /vehicle-types/**, /auth/**

management:
  tracing:
    sampling:
      probability: 1.0

app:
  jwt-secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b






